# Use root/example as user/password credentials
version: '3.1'

services:
  xxl-job-executor:
    image: "xxl-job-executor:latest"
    restart: always
    scale: 3
    ports:
      - "9999-10014:9999"
    depends_on: 
      - xxl-job-admin
  xxl-job-admin:
    image: "xxl-job-admin:latest"
    container_name: xxl-job-admin
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/my.cnf.d/my_custom.cnf:ro
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=Yunjikeji#123
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    restart: always
